version: "3.8"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.9
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false # Disable security for development
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms1g -Xmx1g # JVM heap size
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"

volumes:
    esdata:
